# -*- coding: utf-8 -*-
#
# Copyright (C) 2020 CESNET.
#
# CESNET OA Publications Repository is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

version: '2.3'
services:
  cache:
    image: redis
    restart: "always"
    read_only: true
  db:
    image: postgres:9.6
    restart: "always"
    environment:
      - "POSTGRES_USER=uct-repository"
      - "POSTGRES_PASSWORD=uct-repository"
      - "POSTGRES_DB=uct-repository"
  mq:
    image: rabbitmq:3-management
    restart: "always"
  es7:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.6.0
    restart: "always"
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
